on: 
  push: {}

jobs:
  export_game:
    runs-on: ubuntu-latest
    permissions: write-all # Allow release creation
    name: Export Game
    steps:
    - name: checkout
      uses: actions/checkout@v4
  
    - name: export game
      id: export
      uses: firebelley/godot-export@v5.2.1
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_linux.x86_64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_export_templates.tpz
        relative_project_path: ./
        archive_output: true

    - name: create release
      uses: ncipollo/release-action@v1.14.0
      with:
        generateReleaseNotes: true
        tag: ${{ github.ref_name }}
        artifacts: ${{ steps.export.outputs.archive_directory }}/*

